### ISSUE TITLE
Uknown character set of file

### ISSUE THREAD

**Issue by livarb** [innovationnorway/analysis-innovation-policy-data#1]
I can't figure out what charset the file is encoded with.
æøå-characters are scrambled. I suspect that it's something wrong with the file.
Could you please look into this? And state what charset is used in the README.

**Comment by sigridg** [comment]
Thanks for the comment and sorry about the delay in respons. I am new to GitHub and did not see this issue . I have now updated a new version of the data with UTF-8 encoding. Let me know if this do not solve your problem
